# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Create release from a tag

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /
      
jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Unit Tests with Gradle
      run: ./gradlew test
          
  create_releases:
    name: "Create Release"
    
    permissions:
      contents: write

    runs-on: "ubuntu-latest"
    
    needs: build_test

    steps:
      - uses: actions/checkout@v2
      - name: Retrieve saved artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: "./artifacts"
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: "./artifacts"
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./artifacts/build/libs/*, ./artifacts/docs/*"
